import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import { NextAuthProvider } from "./sessionProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
                    // integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" 
                    />
            </head>
            <body className={inter.className}>
                <NextAuthProvider>
                    <div className='gradient width-100%'></div>
                    {children}
                </NextAuthProvider>
            </body>
        </html>
    )
}
